### PR TITLE
Add 1st formal checks of GPIO peripheral

### PR DESCRIPTION
**Pull request by tmeissner**
I've began tries to formally verify parts of the NEORV32 processor system :hammer: 

The CPU core could be verified with riscv-formal in future. But the peripherals can be verified with good old PSL properties using GHDL & SymbiYosys.

Here is a first small step: 

The unit I've chosen to begin is the GPIO peripheral, because it's dead simple :smile:
Not all necessary properties are formulated yet, but more will come in near future.

I will integrate the tests in CI later. We could let this PR in WIP state until them are added if you want.

BTW: I've hit a GHDL bug right with the first property I've written. The `next_e` operator behavior seems to be wrong under certain conditions. I've rewritten the properties until that operator is fixed.

### CODE REVIEW

**Comment by tmeissner** [comment]
I've added some more checks about GPIO in- & output behavior. Furthermore assumptions about bus behavior, which are based on the relevant sections of the NEORV32 documentation.  As these assumptions are valid for all peripheral modules, they will be moved into a reusable module later.

I'm on vacation the next 10 days, so I will continue working on this PR when I'm back from the warm south 🙂

**Comment by tmeissner** [comment]
I moved the bus protocol modelling into a separate entity to enabling reuse in other coming checks.
I think we could start with the current state of this PR - I'm  open for your reviews & comments 🙂

**Comment by stnolting** [comment]
Hey there! Sorry for the late reply... 🙈

I hope you had some nice holidays! ;)

> I've began tries to formally verify parts of the NEORV32 processor system 🔨

This is really **really** great! Thanks for all your effort and work!

Recently, I also put an eye on https://github.com/SymbioticEDA/riscv-formal as a formally verified setup might be something nice to have (https://github.com/stnolting/neorv32/issues/412). However, I am complete beginner when it comes to formal verification... 😅

> I think we could start with the current state of this PR - I'm open for your reviews & comments 🙂

This is quite heavy (in a good way!). I was thinking about setting up just another repository (maybe `neorv32-verif`) to keep all the verification-based things out of the base repository (just the way we did with the example setup in [neorv32-setups](https://github.com/stnolting/neorv32-setups) or RISC-V ISA check in [neorv32-riscof](https://github.com/stnolting/neorv32-riscof)).

We could add the base core as submodule, do all the CI things over there and add another status badge here in this repository (-> [_Project Status_](https://github.com/stnolting/neorv32#Project-Status)). What do you think about this?

**Comment by tmeissner** [comment]
> This is quite heavy (in a good way!). I was thinking about setting up just another repository (maybe `neorv32-verif`) to keep all the verification-based things out of the base repository (just the way we did with the example setup in [neorv32-setups](https://github.com/stnolting/neorv32-setups) or RISC-V ISA check in [neorv32-riscof](https://github.com/stnolting/neorv32-riscof)).
> 
> We could add the base core as submodule, do all the CI things over there and add another status badge here in this repository (-> [_Project Status_](https://github.com/stnolting/neorv32#Project-Status)). What do you think about this?

A separate repository for verification stuff is a good idea, if we ensure that the CI tests in it are run automatically triggered by activity in the NEORV32 main repo. I'm not that experienced with Github Actions, but I think, that should be possible.

Maybe we should start with the formal stuff and move the simulation things later when the CI infrastructure is established.

**Comment by stnolting** [comment]
> A separate repository for verification stuff is a good idea, if we ensure that the CI tests in it are run automatically triggered by activity in the NEORV32 main repo. I'm not that experienced with Github Actions, but I think, that should be possible.

Sounds good! Basically, we are using such a "trigger" already for the NEORV32 RISCOF repository.

I will setup a new repository and then we can start the formal verification _experience_ over there :wink:

> Maybe we should start with the formal stuff and move the simulation things later when the CI infrastructure is established.

👍

**Comment by tmeissner** [comment]
I've seen that there already exists a repository called `neorv32-verif`. We could reuse that archived repository or create a new one. Maybe it would also be useful to have separate repositories for simulation and formal verification. So a repository called `neorv32-formal` could used for this PR and stuff coming in future.

**Comment by stnolting** [comment]
> I've seen that there already exists a repository called neorv32-verif

This one is outdated and replaced by [neorv32-riscof](https://github.com/stnolting/neorv32-riscof). I just wanted to keep this (archived) as it shows how to make a port of the "old" RISC-V architecture test framework.

> So a repository called neorv32-formal could used for this PR and stuff coming in future.

That sounds good! :1+:

**Comment by stnolting** [comment]
There we go: https://github.com/stnolting/neorv32-formal 😄

**Comment by tmeissner** [comment]
Closed in favor of stnolting/neorv32-formal#1

**Pull request closed without merging**
