### PR TITLE
[rtl/core] fixing SLINK IRQ bug #199

### PR DESCRIPTION
**Pull request by stnolting**
This PR aims to fix the bug in SLINK's interrupt signal logic from #199.

@LeFl0w

### CODE REVIEW

**Comment by stnolting** [comment]
@LeFl0w You're ok with the modifications?

**Comment by LeFl0w** [comment]
I'm not sure about changes for lines 263 and 277.
You come from an iteration over only  the implemented Slink bits to an iteration over every possible links numbers (even unimplemented ones).
This will produce dead code in case of `SLINK_NUM`_ not equal to 8.

I think you could keep the previous code , as your vector is initialized entirely to a default value with `rx_tmp_v := (others => '0')` and then you iterate over only implemented slink bits.

With your new code I 'll have to analyze how `irq_rx_mode(i)`, `rx_fifo_half(i)` and `rx_fifo_avail(i)`  behave when i is not referring to an implemented slink number. In my point of view it is more complicated to analyze without simulation.

**Comment by stnolting** [comment]
> I'm not sure about changes for lines 263 and 277. This will produce dead code in case of SLINK_NUM_ not equal to 8.

That's right, but the synthesis tool should trim these signals.

I noticed that the MSB-aligned bits of `irq_rx_en` and `irq_tx_en` might not be initialized (not written in the bus write access process) if less than 8 links are implemented. That's where those chances came from.

However, feel free to update this PR with another proposal :wink:

**Comment by stnolting** [comment]
This is obsolete now. See #202.

**Pull request closed without merging**
