### PR TITLE
Added option to print a selected subset of information from processor…

### PR DESCRIPTION
**Pull request by LarsAsplund**
…_check to UART0 during simulation.

### CODE REVIEW

**Comment by stnolting** [comment]
Looks great! :+1:

However, I would like to keep the memory requirements below 16kB - there is some stuff in the test program that is not needed anymore. I think it would be ok to make this a simulation-only test program so we can get rid of some is-simulation checks making the executable a little less smaller. I would do the changes if that is ok for you.

**Comment by LarsAsplund** [comment]
@stnolting That's ok with me.

**Comment by stnolting** [comment]
I made some small edits here. The most importants are:
* IMEM uses the default size of 16kB for simulation
* the UART tests will output 0x00 at the _default_ baudrate (19200); so the testbench receivers will detect 0x00 twice for each UART

**Comment by stnolting** [comment]
Seems to work :wink:
So I think this can be merged if you are ok with the changes @LarsAsplund

**Pull request merged**
