### PR TITLE
add back TWI clock stretching option

### PR DESCRIPTION
**Pull request by stnolting**
requested by @NikLeberg in https://github.com/stnolting/neorv32/pull/865#issuecomment-2029060807

### CODE REVIEW

**Comment by stnolting** [comment]
@NikLeberg 

Do you have a peripheral device available that actually makes use of clock stretching? The simple port expanders and EEPROMs on my desk are also happy without this function.

**Comment by NikLeberg** [comment]
Hi @stnolting, thanks for swiftly bringing this back!

At home I do have the mentioned BNO055 and could test it... but I'm on pretty long backpacker holidays 😇. So I don't have access currently to it for a few months.

Maybe I can come up with a way to simulate and test it.

**Comment by stnolting** [comment]
> but I'm on pretty long backpacker holidays 😇

Now that sounds nice! Which continent are you exploring?

> Maybe I can come up with a way to simulate and test it.

Let's just merge this for now going back to the previous clock stretching mechanism.

**Comment by NikLeberg** [comment]
> Now that sounds nice! Which continent are you exploring?

We did India, currently Nepal and soon south-east asia with Thailand, Vietnam and more. Lets see. Gonna be a few more months. 🏝🤗

**Comment by stnolting** [comment]
Asia is nice. Definitely one of my 7 favorite continents! 😄
Have fun!

**Pull request merged**
