### PR TITLE
:warning: Update / rework SPI module

### PR DESCRIPTION
**Pull request by stnolting**
This PR is rework/update of the processor's SPI module.

* :warning: change control register layout
* :warning: remove configurable transmissions size, SPI operations are fixed to 8-bit
* rework interrupt configuration mechanism (new style 😉)
* improve blockRAM mapping/inference (using FIFO with _synchronous_ read access)

### CODE REVIEW

**Comment by stnolting** [comment]
@akaeba Could you have a loot at the [demo_spi_irq](https://github.com/stnolting/neorv32/tree/main/sw/example/demo_spi_irq) demo program?

**Comment by akaeba** [comment]
> @akaeba Could you have a look at the [demo_spi_irq](https://github.com/stnolting/neorv32/tree/main/sw/example/demo_spi_irq) demo program?

yes i can check.

**Comment by akaeba** [comment]
Driver is changed, but evaluation in simulator is pending.

**Comment by stnolting** [comment]
Seems fine now.
Thanks for updating!

**Pull request merged**
