### PR TITLE
RTL reworks, cleanups and optimizations

### PR DESCRIPTION
**Pull request by stnolting**
* Vivado IP module: major rework; use explicit `std_logic[_vector] <-> std_ulogic[_vector]` conversion; remove VHDL2008 requirement (not supported by the IP packager?)
* CPU: remove output register of multiplier unit to improve mapping to DSP block (`FAST_MUL_EN` option only)
* CPU: :warning: remove user-level HPMs
* CPU: rework `mcountern` CSR; add explicit `CY` and `IR` bits
* CPU: rework "next PC" logic - use ALU adder to compute the next instruction address (removes one carry chain and shortens the critical path of the base CPU core)
* DOCs: updates, cleanups and fixes

### CODE REVIEW

**Review by Sam-Vervaeck — COMMENTED** [review]
I had a look through all the changes, did not see anything weird.

**Comment by stnolting** [comment]
@Sam-Vervaeck Thanks for reviewing! :)

I'm still doing some (synthesis) tests, but everything seems to be fine so far.

**Comment by Sam-Vervaeck** [comment]
@stnolting This is still in the user guide but I think this pull request removed the need for this disclaimer in section 12?
image

**Comment by stnolting** [comment]
You are right! I forgot to remove that... Thanks for pointing that out!

**Pull request merged**
