### PR TITLE
[ci] use eine/tip for uploading artifacts to (pre-)releases

### PR DESCRIPTION
**Pull request by umarcor**
As discussed in #26, this PR brings some of the missing enhancements to CI:

- eine/tip is used for uploading the site and the PDF to a 'nightly' pre-release. The label will be force-pushed for matching the artifacts. Two files are uploaded: the PDF datasheet and a tarball containing the site (HTML datasheet plus doxygen output). See https://github.com/umarcor/neorv32/releases.
- Deployment to GitHub Releases and GitHub Pages is disabled for PRs or non-master non-tagged commits/branches. Commits fron non-master branches which are tagged will be deployed.
- Figures are added to the HTML artifact, and therefore uploaded to GitHub Pages.

### CODE REVIEW

**Comment by stnolting** [comment]
> As discussed in #26, this PR brings some of the missing enhancements to CI:

Great! Thank you very much!

I think I have already modified most of the "_typos_" - I'll check out the conflicts.

**Comment by umarcor** [comment]
I was just reviewing the commits you pushed today and I was about to rebase, so I can handle that for you if you wish.

**Comment by stnolting** [comment]
Thanks 😉

**Comment by umarcor** [comment]
I rebased and pushed. Note that the last commit is mostly for limiting the width of the lines in `docs/src_adoc/on_chip_debugger.adoc`. Unlike other adoc sources, in that one some paragraphs were written in a single row.

**Comment by stnolting** [comment]
> Note that the last commit is mostly for limiting the width of the lines in docs/src_adoc/on_chip_debugger.adoc. Unlike other adoc sources, in that one some paragraphs were written in a single row.

Thanks for all the text fixing! 👍

**Pull request merged**
